# Site settings
title: Andrej ZIRKO
description: ''
url: 'https://www.zirko.eu'
baseurl: ''
profilepic: '/images/zirko.jpeg'
bkimage: '/images/horsky-park-optimized.jpg'
google_analytics: G-49ZKFVV56Z
font_awesome: 'e41ef0af5a.js'

author:
  name: 'Andrej Zirko'
  email: andrej@zirko.eu
  twitter_username: andrej_zirko
  github_username:  andrej-zirko
  linkedin_username:  andrejzirko

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
